name: Build and Push Image to github
on:
  push:
    branches: [ master ]
jobs:
  build-and-push-gcr:
    name: Build and Push to GCP 
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: rsi-api
        PROJECT_ID: rsi-api-test
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Prove source changed
        run: cat src/main/resources/application.properties
      - name: Maven package 
        run: mvn -version
      - name: Maven package 
        run: mvn package 
      - name: Force timestamp to be displayed
        run: date
      - name: Look for target or bin directories
        run: ls -l target/api*.jar
      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{secrets.SERVICE_ACCOUNT_KEY}}
          project_id: ${{env.PROJECT_ID }}
          export_default_credentials: true
      - name: Build Docker image 
        run: docker build -t $IMAGE_NAME:latest .
      
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet 

      - name: Docker Tag as latest
        env:
          GIT_TAG: v0.1.0
        run: 
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
      - name: Docker Tag as specific
        env:
          GIT_TAG: v0.1.0
        run: 
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
      - name: Push Docker Image to Container Registry as latest
        env:
          GIT_TAG: v0.1.0
        run: 
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
      - name: Push Docker Image to Container Registry as specific tag
        env:
          GIT_TAG: v0.1.0
        run: 
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
